tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "jandedobbeleer/oh-my-posh"
tap "thoughtbot/formulae"

brew "curl"
brew "fzf"
brew "gitsh"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jq"
brew "tmux"
brew "wget"
cask "xcodes"
