#!/bin/bash

# Exit early if this script was already sourced
if [[ "${_SUDO_SUPPORT_SOURCED:-}" == "1" ]]; then
    return 0
fi
export _SUDO_SUPPORT_SOURCED=1

SUDO_CREDENTIALS_CACHED_IN_SCRIPT=0

# shellcheck disable=SC2046
kill_sudo_on_exit() {
    trap - EXIT

    # Invalidate the cached credentials, if we're the ones that cached it
    if [[ "$SUDO_CREDENTIALS_CACHED_IN_SCRIPT" -ne "0" ]]; then
        sudo -k
    fi

    # Kill all subprocesses
    kill -9 $(jobs -rp) 2> /dev/null
    wait $(jobs -rp) 2>/dev/null
}
trap kill_sudo_on_exit EXIT

# This will create a background subprocess that will extends
# sudo timeout every 5 seconds.
keep_sudo_alive() {
    while sudo -nv 2> /dev/null; do
        sleep 5
    done
}

# Check to see the credentials were already cached before we got here.
# When we exit, we want to make sure we only invalidate the credentials
# if we were the ones that caused it to be cached.
sudo -nv 2> /dev/null || rv=$?
SUDO_CREDENTIALS_CACHED_IN_SCRIPT="$rv"

sudo -v -p "Enter your password to install: "
keep_sudo_alive &
