#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]
stack = ["log", "-r", "stack"]
forked_stack = ["log", "-r", "descendants(stack)"]
show_current_branch = ["log", "--no-graph", "--ignore-working-copy", "--color=never", "-r", "roots(closest_not_empty(@):: & bookmarks())", "--template", 'bookmarks.join(", ") ++ "\n"']

# Lifted from https://github.com/jj-vcs/jj/discussions/4974
#
#          trunk()..                    All commits not in the trunk
#    roots(trunk()..)                   Take only the root commits of those...
#    roots(trunk()..) & mutable()       ...as long as they're mutable
#
move_everything_to_trunk = ["rebase", "-d", "trunk()", "-s", "roots(trunk().. & mine()) & mutable()"]

[colors]
"diff token" = { underline = false }

[user]
name = "Enrique Osuna"
email = "12620+feosuna1@users.noreply.github.com"

# Configure Kaleidoscope diff and merge tools
[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[ui]
# Uses Git's "diff3" conflict markers to support tools that depend on it
conflict-marker-style = "git"

# The default command to run when `jj` is invoked without arguments.
default-command = ["log", "-r", "coalesce(stack, present(@) | ancestors(immutable_heads().., 2) | trunk())"]

# Render diffs the same as git does.
diff-formatter = ":git"

[revsets]
# When advancing a bookmark, jump to the closest pushable commit.
bookmark-advance-to = 'closest_pushable(@)'

[revset-aliases]

# Returns the stack of commits, from the fork point of trunk() to the descendants of the closest non-empty commit
# reachable from the current commit.
stack = "trunk()..descendants(closest_not_empty(@))"

# The closest revision, that is not empty, that can be pushed to the remote.
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

# Finds the closest non-empty commit reachable from `to`.
'closest_not_empty(to)' = "heads(::to ~ empty() & mine() & mutable())"

# The closest revision, that is not empty, that can be pushed to the remote.
latest_commit = 'heads(::@ & mutable() & (~description(exact:"") | ~empty()))'

# The last commit with un-described changes. Commits with descriptions are considered to be ready to be pushed.
# While commits without descriptions are considered to be in progress.
staged = 'heads(::@ & mutable() & (description(exact:"") & ~empty()))'

[visualjj]
auto-describe = false
snapshot-enabled = false
auto-init = false
show-immutable = false
